### ISSUE TITLE
Reopen internal server (after closing it)

### ISSUE THREAD

**Issue by Laiteux** [MihaZupan/HttpToSocks5Proxy#15]
Hello,

The `HttpToSocks5Proxy` is offering a `StopInternalServer` method.
I'd like to know if you could add a `StartInternalServer` method as well, so we can reopen it.

Some stuff that might be useful: https://stackoverflow.com/a/7945801/12730904

Didn't want to try doing this by myself as I never worked with the `Socket` class before.

Kind regards,
Matt.

**Comment by MihaZupan** [comment]
It's certainly possible to add, I'm just wondering about the benefits (vs just creating a new `HttpToSocks5Proxy`). What is the use case?

**Comment by Laiteux** [comment]
In my app, I'm using what I call a  "HttpClientCache" which basically stores all my HttpClient instances for each user loaded proxy.

I can then retrieve HttpClients from there, instead of creating new ones for new requests, which would reduce performance a lot.

Starting and stopping the server as I want would be really useful since if the user loads like 10K proxies, I won't have 10K servers running.

I'd like a server to be ran only when an HttpClient is needed for use, then when I don't need it anymore, just close the server.

I hope you understand.

Kind regards,
Matt.

**Comment by Laiteux** [comment]
Hey,

Any update about this?

Kind regards,
Matt.
