### ISSUE TITLE
asp.net & HttpParser 

### ISSUE THREAD

**Issue by kiminuo** [MihaZupan/HttpToSocks5Proxy#19]
Hi @MihaZupan,
 
I was thinking: Would it simplify your implementation of `TryReadTarget`, if you were to employ https://github.com/dotnet/aspnetcore/blob/master/src/Servers/Kestrel/Core/src/Internal/Http/HttpParser.cs? It's probably not public API but it seems available. Just asking.

Useful resource: https://stackoverflow.com/questions/318506/converting-raw-http-request-into-httpwebrequest-object#54075677

Cheers!

**Comment by MihaZupan** [comment]
Sorry about never responding to this. I'm archiving this project as support for SOCKS proxies has been added in .NET 6.

Thanks for pointing the parser out. I've used it in other projects and it would indeed offer better performance and correctness.
But as long as the current logic is not completely broken, I am afraid I will not be investing time into improving this library given that support for Socks proxies now exists in .NET 6.
