### ISSUE TITLE
Ports exhaustion 

### ISSUE THREAD

**Issue by d668** [MihaZupan/HttpToSocks5Proxy#3]
`var proxy = new HttpToSocks5Proxy("127.0.0.1", Port);`
causes 
`An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full` after a while. 
Every time a new port opens and never closes. See screen:
![image](https://user-images.githubusercontent.com/2155554/50588437-11048100-0e93-11e9-8795-1840085b2299.png)

Am I supposed to close something?

**Comment by d668** [comment]
![image](https://user-images.githubusercontent.com/2155554/50588488-5923a380-0e93-11e9-9c18-c37a4f936be4.png)

**Comment by d668** [comment]
How can I free `proxy.InternalServerPort`?

**Comment by MihaZupan** [comment]
Are you creating a new proxy and  httpclient for every request?

**Comment by d668** [comment]
yes
```
               var proxy = new HttpToSocks5Proxy("127.0.0.1", Port);
                var handler = new HttpClientHandler { Proxy = proxy };
                using (var httpClient = new System.Net.Http.HttpClient(handler, true))
                {
                    var httpsGet = httpClient.SendAsync(new HttpRequestMessage(HttpMethod.Get, url));
                    try
                    {
                        var str = httpsGet.Result.Content.ReadAsStringAsync().Result;
                        if (!string.IsNullOrEmpty(str))
                        {
                            httpClient.Dispose();
                            return str;
                        }
                    }
                    catch (Exception ex)
                    {
                        HandleError(ex);
                    }
                }
```

when debugging after ` return str;` the port stays in `Listening` state.

**Comment by MihaZupan** [comment]
The Proxy itself is meant to only be instantiated once (for each proxy). It's basicallly hosting an Http proxy server internally.
I can add a function to explicitly stop the internal server (before the application exits). However you should **not** create a new instance of the proxy for each request.

**Comment by d668** [comment]
In my app every request goes using its own proxy, so I need to create a proxy every time. 
I think proxy should release all resources after its object disposal. That's the proper way imho. 
Can you please add this functionality? Thanks!

**Comment by d668** [comment]
Is there some workaround meanwhile? It is a bit urgent, sorry I already switched our app to your proxy and now it doesn't work

**Comment by MihaZupan** [comment]
It will not be implementing IDisposable since `HttpConnectionPoolManager` disposes of proxies if they implement IDisposable.
I'll add a function `StopInternalServer()` that you have to call manually if you want to stop the internal server.

**Comment by d668** [comment]
OK sure! thanks, waiting!

**Comment by MihaZupan** [comment]
Version 1.1.2 pushed to NuGet now

Edit: Now listed

**Comment by MihaZupan** [comment]
Side note: You don't have to call Dispose on the HttpClient since you're already using a `using `block

Out of curiosity, what kind of app are you building that requires proxies for each request?

**Comment by d668** [comment]
testing. seems fine, thanks a ton!
I am under an NDA but basically every connection first creates an SSH channel and then uses it for running HttpClient.

**Comment by d668** [comment]
thanks for a tip about Dispose, I was just going nuts looking for leaks, so I added it :)
