### ISSUE TITLE
Losing query part of URI

### ISSUE THREAD

**Issue by KjellRS** [MihaZupan/HttpToSocks5Proxy#4]
In HttpToSocks5Proxy.cs, line 245-253 you load the full URI but extract only the path, so an URL like /foo?bar=1#today is stripped of both the query part (?bar=1) and fragment (#today). Both of these should be preserved if they're non-empty.

**Comment by MihaZupan** [comment]
I'm glad you cought this!
It should only happen when using an http site and only on the first request, that's why it got overlooked.

**Comment by MihaZupan** [comment]
I've pushed 1.1.3 to NuGet
