### ISSUE TITLE
OnAcceptCallback throw unhandled exception

### ISSUE THREAD

**Issue by ductai230894** [MihaZupan/HttpToSocks5Proxy#6]
I tried throw exception inside the OnAcceptCallback method (HttpToSocks5Proxy class 101), the error always occurs, but cannot be processed inside the try catch block ..

Create an error :
Edit the method OnAcceptCallback throw new exception ("test);
Run test

> > IWebProxy webproxy = new HttpToSocks5Proxy ("127.0.0.1", 5789);
> > Webclient webclient = new Webclient ();
> > webclient.Proxy = webproxy;
> > 
> > try {
> webclient.DownloadString("https://google.com");
> > }
> > catch(Exception e)
> {
> Console.Write("error");
> //Don't throw bugs here
> }

**Comment by MihaZupan** [comment]
The OnAcceptCallback will executed on different threads than your webClient's DownloadString. Therefore you can't catch exceptions there.

What kind of exceptions are being thrown in the OnAcceptCallback?

**Comment by ductai230894** [comment]
thank you, I understood
