### ISSUE TITLE
System.Net.Sockets.SocketException: 'A blocking operation was interrupted by a call to WSACancelBlockingCall

### ISSUE THREAD

**Issue by ductai230894** [MihaZupan/HttpToSocks5Proxy#7]
When I'm using with webclient to post data..
It show error
System.Net.Sockets.SocketException: 'A blocking operation was interrupted by a call to WSACancelBlockingCall on method RelayData ..

It running onther thread, how i can catch this error ??

**Comment by MihaZupan** [comment]
Are you calling `StopInternalServer` and what framework version are you running on?

**Comment by ductai230894** [comment]
I only run 1 thread with Webclient..
But I see 2 thread run RelayData method together, when thread A Run TryDisposeSocket(source) inside RelayData method, thread B will throw exception System.Net.Sockets.SocketException immediately...


Produce exception steps:
using HttpToSocks5Proxy with Webclient
run Webclient.UploadString with data large (maybe 2000 chars)
RelayData method throw exception

I don't call StopInternalServer, My framework which I'm using is 4.5.2

Update 
When I comment TryDisposeSocket(source),TryDisposeSocket(target) in finally block code insde ReplayData method, ReplayData method is throwing System.Net.Sockets.SocketException: 'An existing connection was forcibly closed by the remote host',

**Comment by MihaZupan** [comment]
I've updated the relaying logic now. Can you test again on your side with version 1.2.0?

**Comment by ductai230894** [comment]
Ok. thanks you fixed, love you :D

**Comment by MihaZupan** [comment]
Thank you for the feedback and debugging!
